name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  vet_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...